---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 7dc9fcdb7f51ee38f9df291040c3f281484dc62f
    fabric8.io/iconUrl: img/icons/vertx.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: project-service
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: com.freelance
  name: project-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: project-service
    provider: fabric8
    group: com.freelance
