---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 7dc9fcdb7f51ee38f9df291040c3f281484dc62f
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      app: project-service
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: com.freelance
    name: project-service
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: project-service
      provider: fabric8
      group: com.freelance
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 7dc9fcdb7f51ee38f9df291040c3f281484dc62f
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=project-service&var-version=1.0.0-SNAPSHOT
    labels:
      app: project-service
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: com.freelance
    name: project-service
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: project-service
      provider: fabric8
      group: com.freelance
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 7dc9fcdb7f51ee38f9df291040c3f281484dc62f
          fabric8.io/iconUrl: img/icons/vertx.svg
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=project-service&var-version=1.0.0-SNAPSHOT
        labels:
          app: project-service
          provider: fabric8
          version: 1.0.0-SNAPSHOT
          group: com.freelance
      spec:
        containers:
        - env:
          - name: APP_CONFIGMAP_NAME
            value: project-service
          - name: APP_CONFIGMAP_KEY
            value: app-config.yml
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: project-service:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: vertx
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - vertx
        from:
          kind: ImageStreamTag
          name: project-service:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: project-service
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: com.freelance
    name: project-service
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: project-service
